// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujphumewkihyilmplaxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcGh1bWV3a2loeWlsbXBsYXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDM5OTYsImV4cCI6MjA2NTkxOTk5Nn0.zLgYVsz_A9piJKgIP0avfvX8DxvVNUkk24n63EHwqWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);